QuinielaUI/Areas/Admin/Controllers/PlayersController.cs
using Castle.Core.Internal;
using Helpers;
using Microsoft.AspNetCore.Mvc;
using QuinielaUI.Areas.Admin.Models;
using QuinielaUI.Models;
using Respository;

namespace QuinielaUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlayersController : Controller
    {
        private readonly ILogger<PlayersController> _logger;
        private readonly QuinielaContext _quinielaContext;

        public PlayersController(ILogger<PlayersController> logger, QuinielaContext quinielaContext)
        {
            _logger = logger;
            _quinielaContext = quinielaContext;
        }

        [AuthenticationFilter("ViewAdminUsers")]
        public IActionResult Index()
        {
            List<PlayerDTO> players = _quinielaContext.Players.OrderBy(p => p.Name).Select(p => new PlayerDTO()
            {
                Id = p.Id,
                Name = p.Name
            }).ToList();
            return View(players);
        }

        [AuthenticationFilter("ViewAdminUsers")]
        [HttpGet]
        public IActionResult PlayersTable(int? newPlayerId)
        {
            List<PlayerDTO> players = _quinielaContext.Players.OrderBy(p => p.Name).Select(p => new PlayerDTO()
            {
                Id = p.Id,
                Name = p.Name
            }).ToList();

            if (newPlayerId.HasValue)
            {
                PlayerDTO newPlayer = players.First(p => p.Id == newPlayerId);
                players.Remove(newPlayer);
                players = players.Prepend(newPlayer).ToList();
            }

            ViewBag.NewPLayerId = newPlayerId;
            return PartialView("_PlayersTable", players);
        }

        [AuthenticationFilter("AddAdminUsers")]
        [HttpPost]
        public JsonResult Add(string name)
        {
            name = name.Trim();
            ServiceResponse response = new ServiceResponse()
            {
                errors = new List<string>() { "UnhandedError" }
            };

            if (!name.IsNullOrEmpty())
            {
                Entities.Player player = _quinielaContext.Players.FirstOrDefault(p => p.Name == name);
                if (player == null)
                {
                    try
                    {
                        player = new Entities.Player()
                        {
                            Name = name,
                            Rols = _quinielaContext.Rols.Where(r => r.Id == "Player").ToList()
                        };

                        _quinielaContext.Players.Add(player);
                        _quinielaContext.SaveChanges();

                        response = new ServiceResponse()
                        {
                            data = new PlayerDTO()
                            {
                                Id = player.Id,
                                Name = player.Name
                            }
                        };
                    }
                    catch (Exception e)
                    {
                        this._logger.LogError("PlayersController Add", e);
                    }
                }
                else
                {
                    response = new ServiceResponse()
                    {
                        errors = new List<string>() { "AlreadyExist" }
                    };
                }
            }
            else
            {
                response = new ServiceResponse()
                {
                    errors = new List<string>() { "NameEmpty" }
                };
            }

            return new JsonResult(response);
        }


        [AuthenticationFilter("GenerateLinkAdminUsers")]
        [HttpGet]
        public JsonResult GenerateLink(int playerId)
        {
            ServiceResponse response = new ServiceResponse()
            {
                errors = new List<string>() { "UnhandedError" }
            };

            Entities.Player player = _quinielaContext.Players.Find(playerId);
            if (player != null)
            {
                HelperJWT helper = new HelperJWT();
                string token = helper.GenerateToken(player.Id);
                var baseUri = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
                response = new ServiceResponse()
                {
                    data = baseUri + $"/?playerToken=" + token
                };
            }
            return new JsonResult(response);
        }
    }
}

QuinielaUI/Areas/Player/Controllers/QuinielasController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using QuinielaUI.Areas.Admin.Controllers;
using QuinielaUI.Areas.Player.Models;
using QuinielaUI.Models;
using Respository;
using System.Text.RegularExpressions;

namespace QuinielaUI.Areas.Player.Controllers
{
    [Area("Player")]
    public class QuinielasController : Controller
    {
        private readonly ILogger<QuinielasController> _logger;
        private readonly QuinielaContext _quinielaContext;

        public QuinielasController(ILogger<QuinielasController> logger, QuinielaContext quinielaContext)
        {
            _logger = logger;
            _quinielaContext = quinielaContext;
        }

        public bool Ended { get; private set; }

        [AuthenticationFilter()]
        public IActionResult Index()
        {
            int playerId = int.Parse(HttpContext.Response.Headers["playerId"].ToString());

            var quinielas2 = _quinielaContext.Quinielas.Where(q => q.StartDate <= DateTime.Now.AddDays(5)).ToList();

            List<QuinielaDTO> quinielas = _quinielaContext.Quinielas.Where(q => q.StartDate <= DateTime.Now.AddDays(5)).Select(q => new QuinielaDTO()
            {
                Id = q.Id,
                StartDate = q.StartDate,
                TournamentName = q.Tournament.Name,
                EndDate = q.EndDate,
                Ended = DateTime.Now > q.EndDate,
                NumberOfMatches = q.Matchs.Count(),
                Name = q.Name,
                MatchesResume = q.Matchs.Select(m =>
                    new MatchesResumeDTO()
                    {
                        Id = m.Id,
                        LocalId = m.LocalId,
                        LocalName = m.Local.Name,
                        VisitorId = m.VisitorId,
                        VisitorName = m.Visitor.Name,
                        LocalGoals = m.LocalGoals,
                        VisitorGoals = m.VisitorGoals,
                        Date = m.Date,
                        Ended = m.Ended
                    }).ToList()
            }).ToList();

            quinielas.ForEach(q =>
            {
                q.Hits = 0;
                q.MatchesResume.ForEach(mr =>
                {
                    PlayerGameResult playerMatchResult = _quinielaContext.PlayerGameResult.FirstOrDefault(pgr => pgr.PlayerId == playerId && pgr.MatchId == mr.Id);
                    if (playerMatchResult != null)
                    {
                        mr.PlayerResult = playerMatchResult.Result;
                    }
                    if (mr.IsHit())
                    {
                        q.Hits += 1;
                    }
                });
            });

            quinielas = quinielas.OrderBy(q => q.Ended).ThenBy(q => q.EndDate).ToList();
            return View(quinielas);
        }

        [AuthenticationFilter()]
        public IActionResult Edit(int quinielaId)
        {
            int playerId = int.Parse(HttpContext.Response.Headers["playerId"].ToString());

            Quiniela quiniela = _quinielaContext.Quinielas.Find(quinielaId);
            QuinielaDTO model = null;
            if (quiniela != null)
            {

                model = new QuinielaDTO()
                {
                    Id = quiniela.Id,
                    Name = quiniela.Name,
                    TournamentName = quiniela.Tournament.Name,
                    EndDate = quiniela.EndDate,
                    Ended = DateTime.Now > quiniela.EndDate,
                    StartDate = quiniela.StartDate,
                    MatchesResume = new List<MatchesResumeDTO>()
                };

                foreach (Entities.Match match in quiniela.Matchs)
                {
                    PlayerGameResult playerMatchResult = _quinielaContext.PlayerGameResult.FirstOrDefault(pmr => pmr.PlayerId == playerId && pmr.MatchId == match.Id);

                    model.MatchesResume.Add(new MatchesResumeDTO()
                    {
                        Id = match.Id,
                        Group = match.Group,
                        LocalId = match.LocalId,
                        LocalGoals = match.LocalGoals,
                        LocalName = match.Local.Name,
                        Date = match.Date,
                        Ended = match.Ended,
                        VisitorId = match.VisitorId,
                        VisitorGoals = match.VisitorGoals,
                        VisitorName = match.Visitor.Name,
                        CanDraw = match.CanDraw,
                        PlayerResult = playerMatchResult != null ? playerMatchResult.Result : null
                    });
                }
            }

            return View(model);
        }

        [AuthenticationFilter()]
        [HttpPost]
        public IActionResult SaveResult(int matchId, int result)
        {
            int playerId = int.Parse(HttpContext.Response.Headers["playerId"].ToString());

            Entities.Match matchGame = _quinielaContext.Matchs.Find(matchId);

            if (matchGame != null)
            {
                if (matchGame.Quiniela.EndDate > DateTime.Now)
                {
                    PlayerGameResult playerMatchResult = _quinielaContext.PlayerGameResult.FirstOrDefault(pgr => pgr.MatchId == matchId && playerId == playerId);

                    if (playerMatchResult == null)
                    {
                        _quinielaContext.PlayerGameResult.Add(new PlayerGameResult()
                        {
                            PlayerId = playerId,
                            MatchId = matchId,
                            QuestionId = null,
                            Result = result
                        });
                    }
                    else
                    {
                        playerMatchResult.Result = result;
                    }
                    _quinielaContext.SaveChanges();
                }
            }
            return Ok();
        }
    }
}

QuinielaUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuinielaUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuinielaUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons-1.9.1/bootstrap-icons.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuinielaUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Player" asp-controller="Quinielas" asp-action="Index">Mis quinielas</a>
                        </li>
                        @if (User.IsInRole("ViewAdminUsers"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administrar
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @if (User.IsInRole("ViewAdminUsers"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Players" asp-action="Index">Administrar Jugadores</a>
                                        </li>
                                    }
                                </ul>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @if (User.IsInRole("ViewAdminMatch"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Players" asp-action="Index">Administrar Partidos</a>
                                        </li>
                                    }
                                </ul>
                            </li>
                        }

                    </ul>
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="nav-item">
                        <a class="navbar-text" href="#">@User.Identity.Name</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Close">Cerrar Session</a>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - QuinielaUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>